# Generated by Django 3.1.3 on 2020-11-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('reader', 'Reader')], max_length=255),
        ),
    ]
